version: '3'

services:
  backend_pm:
    container_name: backend_pm
    build: 
      context: backend
      dockerfile: Dockerfile
    image: backend_pm
    env_file: .env
    ports:
      - '3000:3001'
    depends_on:
      - db
    restart: always
    networks:
      - backend_pm
  frontend_pm:
    container_name: frontend_pm
    build: 
      context: frontend
      dockerfile: Dockerfile
    image: frontend_pm
    env_file: .env
    ports:
      - '8285:80'
    restart: always
    networks:
      - frontend_pm
  db:
    container_name: db
    image: postgres:14-alpine
    env_file: .env
    restart: always
    volumes:
      - db_data:/data/db
    networks:
      - backend_pm
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - backend_pm
volumes:
  db_data:
networks:
  backend_pm:
  frontend_pm:
